// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RentAPI.Data;

namespace RentAPI.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20200110212404_Rent_Added")]
    partial class Rent_Added
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("RentAPI.Data.Rent", b =>
                {
                    b.Property<Guid>("RentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ScooterInstanceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("RentId");

                    b.ToTable("Rents");

                    b.HasData(
                        new
                        {
                            RentId = new Guid("3666b1ef-c954-4b2a-b97a-5cc9a7ca12f8"),
                            IsCancelled = false,
                            LocationId = new Guid("e5cf7f23-0146-4a4a-8322-d1209cf737d0"),
                            RentDate = new DateTime(2019, 1, 3, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            ScooterInstanceId = new Guid("47364138-912d-4ea2-b59f-eca02e4d8db7"),
                            UserId = new Guid("843e8cb6-4928-4bb8-85ca-2412ff36a3eb")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
