// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RentAPI.Data;

namespace RentAPI.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("RentAPI.Data.Rent", b =>
                {
                    b.Property<Guid>("RentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ScooterInstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("RentId");

                    b.ToTable("Rents");

                    b.HasData(
                        new
                        {
                            RentId = new Guid("f2c7dbe2-9f6c-4219-9240-9610ca09b3d9"),
                            EndDate = new DateTime(2000, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCancelled = false,
                            LocationId = new Guid("e5cf7f23-0146-4a4a-8322-d1209cf747d0"),
                            OrderDate = new DateTime(2020, 1, 11, 13, 32, 56, 100, DateTimeKind.Utc).AddTicks(2104),
                            ScooterInstanceId = new Guid("47364138-912d-4ea2-b59f-eca02e4d8db7"),
                            StartDate = new DateTime(1999, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("843e8cb6-4928-4bb8-85ca-2412ff35a3eb")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
